# Generated by Django 5.2.15 on 2026-07-03 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('HEALTH_CENTER', 'Health Center'), ('DISPENSARY', 'Dispensary'), ('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy')], default='HOSPITAL', max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('osm_id', models.CharField(blank=True, help_text="OSM element reference, e.g. 'node/123456' or 'way/123456'.", max_length=32, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'health facilities',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='facility_name_idx'), models.Index(fields=['region'], name='facility_region_idx'), models.Index(fields=['latitude', 'longitude'], name='facility_latlng_idx')],
            },
        ),
    ]
