# Generated by Django 5.2.15 on 2026-06-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_patient_ac2240_idx',
            old_name='billing_inv_patient_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_status_996e80_idx',
            old_name='billing_inv_status_due_idx',
        ),
    ]
