# Generated by Django 5.2.15 on 2026-07-03 07:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_savedpaymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=8)),
                ('per_minute_wait_rate', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=8)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=8)),
                ('basic_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('wheelchair_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=4)),
                ('medical_equipment_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('peak_hour_surcharge_pct', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=4)),
                ('urban_zone_surcharge_pct', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4)),
                ('urban_zone_center_lat', models.DecimalField(decimal_places=6, default=Decimal('-6.792400'), max_digits=9)),
                ('urban_zone_center_lng', models.DecimalField(decimal_places=6, default=Decimal('39.208300'), max_digits=9)),
                ('urban_zone_radius_km', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_active', '-updated_at'),
            },
        ),
    ]
