# Generated by Django 5.2.15 on 2026-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='iv_drip_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_escort_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='oxygen_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='mobility_needs',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('WHEELCHAIR', 'Wheelchair'), ('STRETCHER', 'Stretcher'), ('WALKER_CRUTCHES', 'Walker / Crutches')], default='NONE', max_length=20),
        ),
    ]
