# Generated by Django 5.2.15 on 2026-07-14 05:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_iv_drip_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('MEDICAL_RECORD', 'Medical Record'), ('INSURANCE_CARD', 'Insurance Card'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other')], default='MEDICAL_RECORD', max_length=30)),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patientprofile')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
