# Generated by Django 5.2.15 on 2026-06-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_recurring_and_enhanced_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringschedule',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='[0=Mon..6=Sun] for WEEKLY'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='num_attendants',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of accompanying attendants'),
        ),
    ]
