# Generated by Django 5.2.15 on 2026-07-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_add_trip_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='trip_proofs/photos/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='trip_proofs/signatures/'),
        ),
    ]
