# Generated by Django 5.2.15 on 2026-07-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tripmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimated_fare_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='final_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='final_fare_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
