# Generated by Django 5.2.15 on 2026-07-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('trips', '0007_trip_estimated_fare_breakdown_trip_final_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='facilities.healthfacility'),
        ),
    ]
