# Generated by Django 5.2.15 on 2026-07-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_destination_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='iv_drip_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='medical_escort_required',
            field=models.BooleanField(default=False),
        ),
    ]
