# Generated by Django 5.2.15 on 2026-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_recurringschedule_last_generated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
